version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: taste_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: taste_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taste_explorer
    depends_on:
      - mongo

volumes:
  mongo_data:
