version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: recipe_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=foodDB
    networks:
      - recipe-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/foodDB --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/foodDB
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo_data:
    driver: local

networks:
  recipe-network:
    driver: bridge
