version: "3.9"

services:
  mongo:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=foodDB
    volumes:
      - ./backend/data:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/foodDB
    command: ["npm", "run", "dev"]
